package org.oyunstudyosu.sanalika.panels.achievement
{
   import com.oyunstudyosu.enums.RequestDataKey;
   import com.oyunstudyosu.panel.PanelVO;
   import com.oyunstudyosu.sanalika.mock.IExtensionMock;
   
   public class AchievementPanelMock implements IExtensionMock
   {
       
      
      public function AchievementPanelMock()
      {
         super();
      }
      
      public function requestData(param1:String, param2:Object) : Object
      {
         if(param1 == RequestDataKey.ACHIEVEMENT_LIST)
         {
            return {"data":{"achievements":[{
               "id":"00000003565419e091c658e1",
               "type":"ACHIEVEMENT",
               "metaKey":"spendDiamond",
               "currentStep":1,
               "totalStep":3,
               "status":"ONGOING",
               "steps":[{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":18}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":5}
                  }],
                  "step":1,
                  "currentValue":0,
                  "requirementValue":10
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":50}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":10}
                  }],
                  "step":2,
                  "currentValue":0,
                  "requirementValue":100
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":1000}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":100}
                  },{
                     "type":"PRODUCT",
                     "data":{
                        "clip":"Ag4bBtRJ",
                        "quantity":1,
                        "color":0,
                        "countDownType":"AFTERUSE",
                        "lifeTime":3600
                     }
                  }],
                  "step":3,
                  "currentValue":0,
                  "requirementValue":200
               }],
               "rewardSteps":[]
            },{
               "id":"565419f3e4b06080c6f7b3cc",
               "type":"ACHIEVEMENT",
               "metaKey":"spendSanil",
               "currentStep":1,
               "totalStep":3,
               "status":"ONGOING",
               "steps":[{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":10}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":5}
                  }],
                  "step":1,
                  "currentValue":2000,
                  "requirementValue":100
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":50}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":10}
                  }],
                  "step":2,
                  "currentValue":0,
                  "requirementValue":5000
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":1000}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":100}
                  },{
                     "type":"PRODUCT",
                     "data":{
                        "clip":"Ag4bBtRJ",
                        "quantity":1,
                        "color":0,
                        "countDownType":"AFTERUSE",
                        "lifeTime":3600
                     }
                  }],
                  "step":3,
                  "currentValue":0,
                  "requirementValue":20000
               }],
               "rewardSteps":[]
            },{
               "id":"00000003565419e091c658e3",
               "type":"ACHIEVEMENT",
               "metaKey":"catchFish",
               "currentStep":1,
               "totalStep":3,
               "status":"ONGOING",
               "steps":[{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":10}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":5}
                  }],
                  "step":1,
                  "currentValue":0,
                  "requirementValue":1
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":50}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":10}
                  }],
                  "step":2,
                  "currentValue":0,
                  "requirementValue":5
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":1000}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":100}
                  }],
                  "step":3,
                  "currentValue":0,
                  "requirementValue":10
               }],
               "rewardSteps":[]
            },{
               "id":"565419f3e4b06080c6f7b3cd",
               "type":"ACHIEVEMENT",
               "metaKey":"doShopping",
               "currentStep":1,
               "totalStep":3,
               "status":"ONGOING",
               "steps":[{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":10}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":5}
                  }],
                  "step":1,
                  "currentValue":1,
                  "requirementValue":1
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":50}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":10}
                  }],
                  "step":2,
                  "currentValue":0,
                  "requirementValue":5
               },{
                  "rewards":[{
                     "type":"SANIL",
                     "data":{"amount":1000}
                  },{
                     "type":"DIAMOND",
                     "data":{"amount":100}
                  },{
                     "type":"PRODUCT",
                     "data":{
                        "clip":"b2",
                        "quantity":2,
                        "color":0,
                        "countDownType":"AFTERUSE",
                        "lifeTime":3600
                     }
                  }],
                  "step":3,
                  "currentValue":0,
                  "requirementValue":10
               }],
               "rewardSteps":[]
            }]}};
         }
         return null;
      }
      
      public function getInitData() : Object
      {
         return new PanelVO("AchievementPanel","",{});
      }
      
      public function dispatchExtension(param1:uint) : Object
      {
         return null;
      }
   }
}
